/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Dré
 */
public class TelaGerencial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaGerencial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSexo = new javax.swing.ButtonGroup();
        TabbedPanePrincipal = new javax.swing.JTabbedPane();
        PainelLateralProdutos = new javax.swing.JPanel();
        TabbedPaneProdutos = new javax.swing.JTabbedPane();
        PainelConsultaProdutos = new javax.swing.JPanel();
        lblNomeProduto = new javax.swing.JLabel();
        lblModeloProduto = new javax.swing.JLabel();
        txtNomeProduto = new javax.swing.JTextField();
        txtModeloProduto = new javax.swing.JTextField();
        lblCategoriaProduto = new javax.swing.JLabel();
        lblPrecoProduto = new javax.swing.JLabel();
        txtCategoriaProduto = new javax.swing.JTextField();
        txtPrecoProduto = new javax.swing.JTextField();
        lblateProduto = new javax.swing.JLabel();
        txtAteProduto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        btnIncluirProduto = new javax.swing.JButton();
        btnAlterarProduto = new javax.swing.JButton();
        btnExcluirProduto = new javax.swing.JButton();
        PainelDigitarProdutos = new javax.swing.JPanel();
        lblNomePD = new javax.swing.JLabel();
        txtNomePD = new javax.swing.JTextField();
        lblModeloPD = new javax.swing.JLabel();
        txtModeloPD = new javax.swing.JTextField();
        lblCategoriaPD = new javax.swing.JLabel();
        txtCategoriaPD = new javax.swing.JTextField();
        lblFabricantePD = new javax.swing.JLabel();
        txtFabricantePD = new javax.swing.JTextField();
        lblCorPD = new javax.swing.JLabel();
        txtCorPD = new javax.swing.JTextField();
        lblPrecoPD = new javax.swing.JLabel();
        txtPrecoPD = new javax.swing.JTextField();
        lblEstoquePD = new javax.swing.JLabel();
        txtEstoquePD = new javax.swing.JTextField();
        btnOkPD = new javax.swing.JButton();
        btnCancelarPD = new javax.swing.JButton();
        lblProdutos = new javax.swing.JLabel();
        PainelLateralCliente = new javax.swing.JPanel();
        TabbedPaneClientes = new javax.swing.JTabbedPane();
        PainelConsultaClientes = new javax.swing.JPanel();
        lblNomeCliente = new javax.swing.JLabel();
        lblCPFCliente = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        txtCpfCliente = new javax.swing.JTextField();
        lblTelefoneCliente = new javax.swing.JLabel();
        lblCepCliente = new javax.swing.JLabel();
        txtTelefoneCliente = new javax.swing.JTextField();
        txtCepCliente = new javax.swing.JTextField();
        btnConsultarCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableConsultarCliente = new javax.swing.JTable();
        btnIncluirCliente = new javax.swing.JButton();
        btnAlterarCliente = new javax.swing.JButton();
        btnExcluirCliente = new javax.swing.JButton();
        PainelDigitarClientes = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        lblTel = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblEstadoCiv = new javax.swing.JLabel();
        lblDataNasc = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCPF = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        rbtnFemininoCliente = new javax.swing.JRadioButton();
        rbtnMasculinoCliente = new javax.swing.JRadioButton();
        cboxEstadoCiv = new javax.swing.JComboBox<>();
        fTxtDataNasc = new javax.swing.JFormattedTextField();
        lblCep = new javax.swing.JLabel();
        lblLogradouro = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblPais = new javax.swing.JLabel();
        txtCep = new javax.swing.JTextField();
        txtLogradouro = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        txtPais = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblClientes = new javax.swing.JLabel();
        PainelLateralVendas = new javax.swing.JPanel();
        PainelLateralRelatorios = new javax.swing.JPanel();
        PainelHeader = new javax.swing.JPanel();
        btnSair = new javax.swing.JToggleButton();
        lblHeader = new javax.swing.JLabel();
        imgLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabbedPanePrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TabbedPanePrincipal.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        lblNomeProduto.setText("Nome:");

        lblModeloProduto.setText("Modelo:");

        lblCategoriaProduto.setText("Categoria:");

        lblPrecoProduto.setText("Preço:");

        lblateProduto.setText("Até");

        jButton1.setText("Consultar");

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblProdutos);

        btnIncluirProduto.setText("Incluir");

        btnAlterarProduto.setText("Alterar");

        btnExcluirProduto.setText("Excluir");

        javax.swing.GroupLayout PainelConsultaProdutosLayout = new javax.swing.GroupLayout(PainelConsultaProdutos);
        PainelConsultaProdutos.setLayout(PainelConsultaProdutosLayout);
        PainelConsultaProdutosLayout.setHorizontalGroup(
            PainelConsultaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelConsultaProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelConsultaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelConsultaProdutosLayout.createSequentialGroup()
                        .addGroup(PainelConsultaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblModeloProduto)
                            .addComponent(lblNomeProduto))
                        .addGap(18, 18, 18)
                        .addGroup(PainelConsultaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtModeloProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(txtNomeProduto))
                        .addGap(18, 18, 18)
                        .addGroup(PainelConsultaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCategoriaProduto)
                            .addComponent(lblPrecoProduto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelConsultaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCategoriaProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(txtPrecoProduto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblateProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAteProduto)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                    .addGroup(PainelConsultaProdutosLayout.createSequentialGroup()
                        .addComponent(btnIncluirProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterarProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluirProduto)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        PainelConsultaProdutosLayout.setVerticalGroup(
            PainelConsultaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelConsultaProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelConsultaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategoriaProduto)
                    .addComponent(txtCategoriaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelConsultaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelConsultaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPrecoProduto)
                        .addComponent(txtPrecoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblateProduto)
                        .addComponent(txtAteProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelConsultaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblModeloProduto)
                        .addComponent(txtModeloProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelConsultaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluirProduto)
                    .addComponent(btnAlterarProduto)
                    .addComponent(btnExcluirProduto))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        TabbedPaneProdutos.addTab("Consulta", PainelConsultaProdutos);

        lblNomePD.setText("Nome:");

        lblModeloPD.setText("Modelo:");

        lblCategoriaPD.setText("Categoria:");

        lblFabricantePD.setText("Fabricante:");

        lblCorPD.setText("Cor:");

        lblPrecoPD.setText("Preço:");

        lblEstoquePD.setText("Estoque:");

        btnOkPD.setText("OK");

        btnCancelarPD.setText("Cancelar");

        javax.swing.GroupLayout PainelDigitarProdutosLayout = new javax.swing.GroupLayout(PainelDigitarProdutos);
        PainelDigitarProdutos.setLayout(PainelDigitarProdutosLayout);
        PainelDigitarProdutosLayout.setHorizontalGroup(
            PainelDigitarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelDigitarProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelDigitarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnOkPD)
                    .addGroup(PainelDigitarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(PainelDigitarProdutosLayout.createSequentialGroup()
                            .addGroup(PainelDigitarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblModeloPD)
                                .addComponent(lblNomePD))
                            .addGap(28, 28, 28)
                            .addGroup(PainelDigitarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtModeloPD, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                .addComponent(txtNomePD)))
                        .addGroup(PainelDigitarProdutosLayout.createSequentialGroup()
                            .addGroup(PainelDigitarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCategoriaPD)
                                .addComponent(lblFabricantePD)
                                .addComponent(lblCorPD)
                                .addComponent(lblPrecoPD)
                                .addComponent(lblEstoquePD))
                            .addGap(14, 14, 14)
                            .addGroup(PainelDigitarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtEstoquePD, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                .addComponent(txtPrecoPD)
                                .addComponent(txtCorPD)
                                .addComponent(txtFabricantePD)
                                .addComponent(txtCategoriaPD)))))
                .addGap(18, 18, 18)
                .addComponent(btnCancelarPD)
                .addContainerGap(240, Short.MAX_VALUE))
        );
        PainelDigitarProdutosLayout.setVerticalGroup(
            PainelDigitarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelDigitarProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelDigitarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomePD)
                    .addComponent(txtNomePD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelDigitarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModeloPD)
                    .addComponent(txtModeloPD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelDigitarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoriaPD)
                    .addComponent(txtCategoriaPD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(PainelDigitarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFabricantePD)
                    .addComponent(txtFabricantePD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelDigitarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorPD)
                    .addComponent(txtCorPD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelDigitarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecoPD)
                    .addComponent(txtPrecoPD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelDigitarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEstoquePD)
                    .addComponent(txtEstoquePD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(PainelDigitarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOkPD)
                    .addComponent(btnCancelarPD))
                .addContainerGap(203, Short.MAX_VALUE))
        );

        TabbedPaneProdutos.addTab("Digitar", PainelDigitarProdutos);

        lblProdutos.setText("Produtos");

        javax.swing.GroupLayout PainelLateralProdutosLayout = new javax.swing.GroupLayout(PainelLateralProdutos);
        PainelLateralProdutos.setLayout(PainelLateralProdutosLayout);
        PainelLateralProdutosLayout.setHorizontalGroup(
            PainelLateralProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLateralProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelLateralProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TabbedPaneProdutos)
                    .addGroup(PainelLateralProdutosLayout.createSequentialGroup()
                        .addComponent(lblProdutos)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PainelLateralProdutosLayout.setVerticalGroup(
            PainelLateralProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelLateralProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProdutos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabbedPaneProdutos)
                .addContainerGap())
        );

        TabbedPanePrincipal.addTab("Produtos", PainelLateralProdutos);

        lblNomeCliente.setText("Nome:");

        lblCPFCliente.setText("CPF:");

        lblTelefoneCliente.setText("Telefone:");

        lblCepCliente.setText("CEP:");

        btnConsultarCliente.setText("Consultar");

        TableConsultarCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableConsultarCliente);

        btnIncluirCliente.setText("Incluir");

        btnAlterarCliente.setText("Alterar");

        btnExcluirCliente.setText("Excluir");

        javax.swing.GroupLayout PainelConsultaClientesLayout = new javax.swing.GroupLayout(PainelConsultaClientes);
        PainelConsultaClientes.setLayout(PainelConsultaClientesLayout);
        PainelConsultaClientesLayout.setHorizontalGroup(
            PainelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelConsultaClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelConsultaClientesLayout.createSequentialGroup()
                        .addComponent(lblNomeCliente)
                        .addGap(18, 18, 18)
                        .addGroup(PainelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCpfCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(txtNomeCliente)))
                    .addComponent(lblCPFCliente))
                .addGap(72, 72, 72)
                .addGroup(PainelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCepCliente))
                .addGap(18, 18, 18)
                .addGroup(PainelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTelefoneCliente)
                    .addComponent(txtCepCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConsultarCliente)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
            .addGroup(PainelConsultaClientesLayout.createSequentialGroup()
                .addComponent(btnIncluirCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAlterarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluirCliente)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PainelConsultaClientesLayout.setVerticalGroup(
            PainelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelConsultaClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeCliente)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefoneCliente)
                    .addComponent(txtTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPFCliente)
                    .addComponent(txtCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCepCliente)
                    .addComponent(txtCepCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluirCliente)
                    .addComponent(btnAlterarCliente)
                    .addComponent(btnExcluirCliente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabbedPaneClientes.addTab("Consulta", PainelConsultaClientes);

        lblNome.setText("Nome:");

        lblCPF.setText("CPF:");

        lblTel.setText("Telefone:");

        lblEmail.setText("E-mail:");

        lblSexo.setText("Sexo:");

        lblEstadoCiv.setText("Estado civil:");

        lblDataNasc.setText("Data de nasc:");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        buttonGroupSexo.add(rbtnFemininoCliente);
        rbtnFemininoCliente.setText("Feminino");

        buttonGroupSexo.add(rbtnMasculinoCliente);
        rbtnMasculinoCliente.setText("Masculino");

        cboxEstadoCiv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione:", "Solteiro(a)", "Casado(a)", "Divorciado(a)", "Viúvo(a)" }));

        fTxtDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        lblCep.setText("CEP:");

        lblLogradouro.setText("Logradouro:");

        lblBairro.setText("Bairro:");

        lblCidade.setText("Cidade:");

        lblEstado.setText("Estado:");

        lblPais.setText("País:");

        txtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroActionPerformed(evt);
            }
        });

        btnOK.setText("OK");

        btnCancelar.setText("Cancelar");

        javax.swing.GroupLayout PainelDigitarClientesLayout = new javax.swing.GroupLayout(PainelDigitarClientes);
        PainelDigitarClientes.setLayout(PainelDigitarClientesLayout);
        PainelDigitarClientesLayout.setHorizontalGroup(
            PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelDigitarClientesLayout.createSequentialGroup()
                .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnOK)
                    .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(PainelDigitarClientesLayout.createSequentialGroup()
                            .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblTel)
                                .addComponent(lblEmail)
                                .addComponent(lblSexo))
                            .addGap(26, 26, 26)
                            .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(PainelDigitarClientesLayout.createSequentialGroup()
                                    .addComponent(rbtnFemininoCliente)
                                    .addGap(18, 18, 18)
                                    .addComponent(rbtnMasculinoCliente))
                                .addComponent(txtTel, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                .addComponent(txtEmail)))
                        .addGroup(PainelDigitarClientesLayout.createSequentialGroup()
                            .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNome)
                                .addComponent(lblCPF))
                            .addGap(38, 38, 38)
                            .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNome)
                                .addComponent(txtCPF)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelDigitarClientesLayout.createSequentialGroup()
                            .addComponent(lblDataNasc)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(fTxtDataNasc))
                        .addGroup(PainelDigitarClientesLayout.createSequentialGroup()
                            .addComponent(lblEstadoCiv)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cboxEstadoCiv, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(78, 78, 78)
                .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelDigitarClientesLayout.createSequentialGroup()
                        .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCep)
                            .addComponent(lblLogradouro)
                            .addComponent(lblBairro)
                            .addComponent(lblCidade)
                            .addComponent(lblEstado)
                            .addComponent(lblPais))
                        .addGap(32, 32, 32)
                        .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCep)
                            .addComponent(txtLogradouro)
                            .addComponent(txtBairro)
                            .addComponent(txtCidade)
                            .addComponent(txtEstado)
                            .addComponent(txtPais, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)))
                    .addComponent(btnCancelar))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        PainelDigitarClientesLayout.setVerticalGroup(
            PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelDigitarClientesLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPF)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTel)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbtnFemininoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbtnMasculinoCliente))
                    .addComponent(lblSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstadoCiv)
                    .addComponent(cboxEstadoCiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataNasc)
                    .addComponent(fTxtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnCancelar))
                .addContainerGap())
            .addGroup(PainelDigitarClientesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCep))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLogradouro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBairro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCidade))
                .addGap(11, 11, 11)
                .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPais))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabbedPaneClientes.addTab("Digitar", PainelDigitarClientes);

        lblClientes.setText("Clientes");

        javax.swing.GroupLayout PainelLateralClienteLayout = new javax.swing.GroupLayout(PainelLateralCliente);
        PainelLateralCliente.setLayout(PainelLateralClienteLayout);
        PainelLateralClienteLayout.setHorizontalGroup(
            PainelLateralClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLateralClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelLateralClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TabbedPaneClientes)
                    .addGroup(PainelLateralClienteLayout.createSequentialGroup()
                        .addComponent(lblClientes)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PainelLateralClienteLayout.setVerticalGroup(
            PainelLateralClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelLateralClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabbedPaneClientes)
                .addContainerGap())
        );

        TabbedPanePrincipal.addTab("Clientes", PainelLateralCliente);

        javax.swing.GroupLayout PainelLateralVendasLayout = new javax.swing.GroupLayout(PainelLateralVendas);
        PainelLateralVendas.setLayout(PainelLateralVendasLayout);
        PainelLateralVendasLayout.setHorizontalGroup(
            PainelLateralVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 643, Short.MAX_VALUE)
        );
        PainelLateralVendasLayout.setVerticalGroup(
            PainelLateralVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );

        TabbedPanePrincipal.addTab("Vendas", PainelLateralVendas);

        javax.swing.GroupLayout PainelLateralRelatoriosLayout = new javax.swing.GroupLayout(PainelLateralRelatorios);
        PainelLateralRelatorios.setLayout(PainelLateralRelatoriosLayout);
        PainelLateralRelatoriosLayout.setHorizontalGroup(
            PainelLateralRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 643, Short.MAX_VALUE)
        );
        PainelLateralRelatoriosLayout.setVerticalGroup(
            PainelLateralRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );

        TabbedPanePrincipal.addTab("Relatórios", PainelLateralRelatorios);

        PainelHeader.setBackground(new java.awt.Color(51, 51, 51));
        PainelHeader.setToolTipText("Painel header");

        btnSair.setText("Sair");

        lblHeader.setForeground(new java.awt.Color(204, 204, 204));
        lblHeader.setText("Nome da empresa");

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hacker (1).png"))); // NOI18N

        javax.swing.GroupLayout PainelHeaderLayout = new javax.swing.GroupLayout(PainelHeader);
        PainelHeader.setLayout(PainelHeaderLayout);
        PainelHeaderLayout.setHorizontalGroup(
            PainelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PainelHeaderLayout.setVerticalGroup(
            PainelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelHeaderLayout.createSequentialGroup()
                .addGroup(PainelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelHeaderLayout.createSequentialGroup()
                        .addContainerGap(7, Short.MAX_VALUE)
                        .addGroup(PainelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSair)
                            .addComponent(lblHeader)))
                    .addComponent(imgLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TabbedPanePrincipal)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PainelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabbedPanePrincipal))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerencial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerencial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerencial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerencial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGerencial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelConsultaClientes;
    private javax.swing.JPanel PainelConsultaProdutos;
    private javax.swing.JPanel PainelDigitarClientes;
    private javax.swing.JPanel PainelDigitarProdutos;
    private javax.swing.JPanel PainelHeader;
    private javax.swing.JPanel PainelLateralCliente;
    private javax.swing.JPanel PainelLateralProdutos;
    private javax.swing.JPanel PainelLateralRelatorios;
    private javax.swing.JPanel PainelLateralVendas;
    private javax.swing.JTabbedPane TabbedPaneClientes;
    private javax.swing.JTabbedPane TabbedPanePrincipal;
    private javax.swing.JTabbedPane TabbedPaneProdutos;
    private javax.swing.JTable TableConsultarCliente;
    private javax.swing.JButton btnAlterarCliente;
    private javax.swing.JButton btnAlterarProduto;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelarPD;
    private javax.swing.JButton btnConsultarCliente;
    private javax.swing.JButton btnExcluirCliente;
    private javax.swing.JButton btnExcluirProduto;
    private javax.swing.JButton btnIncluirCliente;
    private javax.swing.JButton btnIncluirProduto;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnOkPD;
    private javax.swing.JToggleButton btnSair;
    private javax.swing.ButtonGroup buttonGroupSexo;
    private javax.swing.JComboBox<String> cboxEstadoCiv;
    private javax.swing.JFormattedTextField fTxtDataNasc;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCPFCliente;
    private javax.swing.JLabel lblCategoriaPD;
    private javax.swing.JLabel lblCategoriaProduto;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCepCliente;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblCorPD;
    private javax.swing.JLabel lblDataNasc;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEstadoCiv;
    private javax.swing.JLabel lblEstoquePD;
    private javax.swing.JLabel lblFabricantePD;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblLogradouro;
    private javax.swing.JLabel lblModeloPD;
    private javax.swing.JLabel lblModeloProduto;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblNomePD;
    private javax.swing.JLabel lblNomeProduto;
    private javax.swing.JLabel lblPais;
    private javax.swing.JLabel lblPrecoPD;
    private javax.swing.JLabel lblPrecoProduto;
    private javax.swing.JLabel lblProdutos;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTel;
    private javax.swing.JLabel lblTelefoneCliente;
    private javax.swing.JLabel lblateProduto;
    private javax.swing.JRadioButton rbtnFemininoCliente;
    private javax.swing.JRadioButton rbtnMasculinoCliente;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtAteProduto;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCategoriaPD;
    private javax.swing.JTextField txtCategoriaProduto;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtCepCliente;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCorPD;
    private javax.swing.JTextField txtCpfCliente;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtEstoquePD;
    private javax.swing.JTextField txtFabricantePD;
    private javax.swing.JTextField txtLogradouro;
    private javax.swing.JTextField txtModeloPD;
    private javax.swing.JTextField txtModeloProduto;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtNomePD;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtPais;
    private javax.swing.JTextField txtPrecoPD;
    private javax.swing.JTextField txtPrecoProduto;
    private javax.swing.JTextField txtTel;
    private javax.swing.JTextField txtTelefoneCliente;
    // End of variables declaration//GEN-END:variables
}
