package view;

import java.awt.Color;
import controller.*;
import javax.swing.JOptionPane;
import javax.swing.table.*;

public class TelaGerencial extends javax.swing.JFrame {
    /**
     * Creates new form TelaInicial
     */
   
    public TelaGerencial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSexo = new javax.swing.ButtonGroup();
        TabbedPanePrincipal = new javax.swing.JTabbedPane();
        PainelLateralProdutos = new javax.swing.JPanel();
        TabbedPaneProdutos = new javax.swing.JTabbedPane();
        PainelConsultaProdutos = new javax.swing.JPanel();
        lblNomeProduto = new javax.swing.JLabel();
        lblModeloProduto = new javax.swing.JLabel();
        txtNomeProdutoConsultar = new javax.swing.JTextField();
        txtModeloProdutoConsultar = new javax.swing.JTextField();
        lblCategoriaProduto = new javax.swing.JLabel();
        lblPrecoProduto = new javax.swing.JLabel();
        txtCategoriaProdutoConsultar = new javax.swing.JTextField();
        txtPrecoDE = new javax.swing.JTextField();
        lblateProduto = new javax.swing.JLabel();
        txtPrecoATE = new javax.swing.JTextField();
        bntConsultarProduto = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        btnIncluirProduto = new javax.swing.JButton();
        btnAlterarProduto = new javax.swing.JButton();
        btnExcluirProduto = new javax.swing.JButton();
        PainelDigitarProdutos = new javax.swing.JPanel();
        lblNomePD = new javax.swing.JLabel();
        txtNomeProdutoDigitar = new javax.swing.JTextField();
        lblModeloPD = new javax.swing.JLabel();
        txtModeloProdutoDigitar = new javax.swing.JTextField();
        lblCategoriaPD = new javax.swing.JLabel();
        txtCategoriaProdutoDigitar = new javax.swing.JTextField();
        lblFabricantePD = new javax.swing.JLabel();
        txtFabricanteProduto = new javax.swing.JTextField();
        lblCorPD = new javax.swing.JLabel();
        lblPrecoPD = new javax.swing.JLabel();
        lblEstoquePD = new javax.swing.JLabel();
        txtEstoqueProduto = new javax.swing.JTextField();
        btnOkProduto = new javax.swing.JButton();
        btnCancelarProduto = new javax.swing.JButton();
        lblStatusProduto = new javax.swing.JLabel();
        cboCor = new javax.swing.JComboBox<>();
        lblAcaoDigitar = new javax.swing.JLabel();
        txtPrecoProduto = new javax.swing.JFormattedTextField();
        lblProdutos = new javax.swing.JLabel();
        PainelLateralCliente = new javax.swing.JPanel();
        TabbedPaneClientes = new javax.swing.JTabbedPane();
        PainelConsultaClientes = new javax.swing.JPanel();
        lblNomeCliente = new javax.swing.JLabel();
        lblCPFCliente = new javax.swing.JLabel();
        txtNomeClienteConsultar = new javax.swing.JTextField();
        txtCpfConsultar = new javax.swing.JTextField();
        lblTelefoneCliente = new javax.swing.JLabel();
        lblCepCliente = new javax.swing.JLabel();
        txtTelefoneConsultar = new javax.swing.JTextField();
        txtCepConsultar = new javax.swing.JTextField();
        btnConsultarCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableConsultarCliente = new javax.swing.JTable();
        btnIncluirCliente = new javax.swing.JButton();
        btnAlterarCliente = new javax.swing.JButton();
        btnExcluirCliente = new javax.swing.JButton();
        PainelDigitarClientes = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        lblTel = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblEstadoCiv = new javax.swing.JLabel();
        lblDataNasc = new javax.swing.JLabel();
        txtNomeClienteDigitar = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        rbtnFemininoCliente = new javax.swing.JRadioButton();
        rbtnMasculinoCliente = new javax.swing.JRadioButton();
        cboEstadoCivil = new javax.swing.JComboBox<>();
        fTxtDataNascimento = new javax.swing.JFormattedTextField();
        lblCep = new javax.swing.JLabel();
        lblLogradouro = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblPais = new javax.swing.JLabel();
        txtLogradouro = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblStatusCliente = new javax.swing.JLabel();
        fTxtCpfDigitar = new javax.swing.JFormattedTextField();
        fTxtTelefone = new javax.swing.JFormattedTextField();
        fTxtCepDigitar = new javax.swing.JFormattedTextField();
        cboPais = new javax.swing.JComboBox<>();
        cboEstado = new javax.swing.JComboBox<>();
        lblNumeroDigitar = new javax.swing.JLabel();
        fTxtNumeroDigitar = new javax.swing.JFormattedTextField();
        lblComplemento = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        lblClientes = new javax.swing.JLabel();
        PainelLateralVendas = new javax.swing.JPanel();
        PainelLateralRelatorios = new javax.swing.JPanel();
        PainelHeader = new javax.swing.JPanel();
        btnSair = new javax.swing.JToggleButton();
        lblHeader = new javax.swing.JLabel();
        imgLogo = new javax.swing.JLabel();
        PainelFooter = new javax.swing.JPanel();
        lblFooter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Gerencial");

        TabbedPanePrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TabbedPanePrincipal.setForeground(new java.awt.Color(242, 242, 242));
        TabbedPanePrincipal.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        PainelLateralProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PainelLateralProdutosMouseClicked(evt);
            }
        });

        TabbedPaneProdutos.setForeground(new java.awt.Color(242, 242, 242));

        lblNomeProduto.setForeground(new java.awt.Color(51, 51, 51));
        lblNomeProduto.setText("Nome:");

        lblModeloProduto.setForeground(new java.awt.Color(51, 51, 51));
        lblModeloProduto.setText("Modelo:");

        lblCategoriaProduto.setForeground(new java.awt.Color(51, 51, 51));
        lblCategoriaProduto.setText("Categoria:");

        lblPrecoProduto.setForeground(new java.awt.Color(51, 51, 51));
        lblPrecoProduto.setText("Preço:");

        lblateProduto.setForeground(new java.awt.Color(51, 51, 51));
        lblateProduto.setText("Até");

        bntConsultarProduto.setText("Consultar");
        bntConsultarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntConsultarProdutoActionPerformed(evt);
            }
        });

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Modelo", "Categoria", "Preço", "Estoque", "Fabricante", "Cor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblProdutos);

        btnIncluirProduto.setText("Incluir");
        btnIncluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirProdutoActionPerformed(evt);
            }
        });

        btnAlterarProduto.setText("Alterar");
        btnAlterarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarProdutoActionPerformed(evt);
            }
        });

        btnExcluirProduto.setText("Excluir");
        btnExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelConsultaProdutosLayout = new javax.swing.GroupLayout(PainelConsultaProdutos);
        PainelConsultaProdutos.setLayout(PainelConsultaProdutosLayout);
        PainelConsultaProdutosLayout.setHorizontalGroup(
            PainelConsultaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelConsultaProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelConsultaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelConsultaProdutosLayout.createSequentialGroup()
                        .addGroup(PainelConsultaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblModeloProduto)
                            .addComponent(lblNomeProduto))
                        .addGap(18, 18, 18)
                        .addGroup(PainelConsultaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtModeloProdutoConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(txtNomeProdutoConsultar))
                        .addGap(18, 18, 18)
                        .addGroup(PainelConsultaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCategoriaProduto)
                            .addComponent(lblPrecoProduto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelConsultaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelConsultaProdutosLayout.createSequentialGroup()
                                .addComponent(txtPrecoDE, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblateProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPrecoATE))
                            .addComponent(txtCategoriaProdutoConsultar))
                        .addGap(18, 18, 18)
                        .addComponent(bntConsultarProduto)
                        .addContainerGap())
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                    .addGroup(PainelConsultaProdutosLayout.createSequentialGroup()
                        .addComponent(btnIncluirProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAlterarProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluirProduto)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        PainelConsultaProdutosLayout.setVerticalGroup(
            PainelConsultaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelConsultaProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelConsultaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeProdutoConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategoriaProduto)
                    .addComponent(txtCategoriaProdutoConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelConsultaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelConsultaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPrecoProduto)
                        .addComponent(txtPrecoDE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblateProduto)
                        .addComponent(txtPrecoATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bntConsultarProduto)
                        .addComponent(txtModeloProdutoConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblModeloProduto, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelConsultaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluirProduto)
                    .addComponent(btnAlterarProduto)
                    .addComponent(btnExcluirProduto))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        TabbedPaneProdutos.addTab("Consulta", PainelConsultaProdutos);

        lblNomePD.setForeground(new java.awt.Color(51, 51, 51));
        lblNomePD.setText("Nome:");

        txtNomeProdutoDigitar.setBackground(new java.awt.Color(255, 221, 40));
        txtNomeProdutoDigitar.setToolTipText("Campo obrigatório");
        txtNomeProdutoDigitar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeProdutoDigitarFocusLost(evt);
            }
        });

        lblModeloPD.setForeground(new java.awt.Color(51, 51, 51));
        lblModeloPD.setText("Modelo:");

        lblCategoriaPD.setForeground(new java.awt.Color(51, 51, 51));
        lblCategoriaPD.setText("Categoria:");

        txtCategoriaProdutoDigitar.setBackground(new java.awt.Color(255, 221, 40));
        txtCategoriaProdutoDigitar.setToolTipText("Campo obrigatório");
        txtCategoriaProdutoDigitar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCategoriaProdutoDigitarFocusLost(evt);
            }
        });

        lblFabricantePD.setForeground(new java.awt.Color(51, 51, 51));
        lblFabricantePD.setText("Fabricante:");

        lblCorPD.setForeground(new java.awt.Color(51, 51, 51));
        lblCorPD.setText("Cor:");

        lblPrecoPD.setForeground(new java.awt.Color(51, 51, 51));
        lblPrecoPD.setText("Preço:");

        lblEstoquePD.setForeground(new java.awt.Color(51, 51, 51));
        lblEstoquePD.setText("Estoque:");

        txtEstoqueProduto.setBackground(new java.awt.Color(255, 221, 40));
        txtEstoqueProduto.setToolTipText("Campo obrigatório");
        txtEstoqueProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEstoqueProdutoFocusLost(evt);
            }
        });
        txtEstoqueProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEstoqueProdutoKeyTyped(evt);
            }
        });

        btnOkProduto.setText("OK");
        btnOkProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkProdutoActionPerformed(evt);
            }
        });

        btnCancelarProduto.setText("Cancelar");
        btnCancelarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarProdutoActionPerformed(evt);
            }
        });

        lblStatusProduto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblStatusProduto.setForeground(new java.awt.Color(51, 255, 0));
        lblStatusProduto.setText("STATUS: VÁLIDO");

        cboCor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sem cor", "Amarelo", "Azul", "Branco", "Preto", "Vermelho" }));

        lblAcaoDigitar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAcaoDigitar.setForeground(new java.awt.Color(51, 51, 51));
        lblAcaoDigitar.setText("Inserir");

        txtPrecoProduto.setBackground(new java.awt.Color(255, 221, 40));
        txtPrecoProduto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtPrecoProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrecoProdutoFocusLost(evt);
            }
        });
        txtPrecoProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrecoProdutoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout PainelDigitarProdutosLayout = new javax.swing.GroupLayout(PainelDigitarProdutos);
        PainelDigitarProdutos.setLayout(PainelDigitarProdutosLayout);
        PainelDigitarProdutosLayout.setHorizontalGroup(
            PainelDigitarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelDigitarProdutosLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(PainelDigitarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelDigitarProdutosLayout.createSequentialGroup()
                        .addComponent(lblAcaoDigitar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PainelDigitarProdutosLayout.createSequentialGroup()
                        .addGroup(PainelDigitarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PainelDigitarProdutosLayout.createSequentialGroup()
                                .addGroup(PainelDigitarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblModeloPD)
                                    .addComponent(lblNomePD))
                                .addGap(28, 28, 28)
                                .addGroup(PainelDigitarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtModeloProdutoDigitar, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                    .addComponent(txtNomeProdutoDigitar)))
                            .addGroup(PainelDigitarProdutosLayout.createSequentialGroup()
                                .addGroup(PainelDigitarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCategoriaPD)
                                    .addComponent(lblFabricantePD)
                                    .addComponent(lblCorPD)
                                    .addComponent(lblPrecoPD)
                                    .addComponent(lblEstoquePD))
                                .addGap(14, 14, 14)
                                .addGroup(PainelDigitarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEstoqueProduto)
                                    .addComponent(txtFabricanteProduto)
                                    .addComponent(txtCategoriaProdutoDigitar, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                    .addComponent(cboCor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPrecoProduto))))
                        .addContainerGap(323, Short.MAX_VALUE))
                    .addGroup(PainelDigitarProdutosLayout.createSequentialGroup()
                        .addComponent(lblStatusProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOkProduto)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarProduto)
                        .addGap(246, 246, 246))))
        );
        PainelDigitarProdutosLayout.setVerticalGroup(
            PainelDigitarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelDigitarProdutosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblAcaoDigitar)
                .addGap(18, 18, 18)
                .addGroup(PainelDigitarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomePD)
                    .addComponent(txtNomeProdutoDigitar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelDigitarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModeloPD)
                    .addComponent(txtModeloProdutoDigitar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelDigitarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoriaPD)
                    .addComponent(txtCategoriaProdutoDigitar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(PainelDigitarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFabricantePD)
                    .addComponent(txtFabricanteProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelDigitarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorPD)
                    .addComponent(cboCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelDigitarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecoPD)
                    .addComponent(txtPrecoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelDigitarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEstoquePD)
                    .addComponent(txtEstoqueProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(PainelDigitarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOkProduto)
                    .addComponent(btnCancelarProduto)
                    .addComponent(lblStatusProduto))
                .addGap(15, 15, 15))
        );

        TabbedPaneProdutos.addTab("Digitar", PainelDigitarProdutos);

        lblProdutos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblProdutos.setForeground(new java.awt.Color(51, 51, 51));
        lblProdutos.setText("Produtos");

        javax.swing.GroupLayout PainelLateralProdutosLayout = new javax.swing.GroupLayout(PainelLateralProdutos);
        PainelLateralProdutos.setLayout(PainelLateralProdutosLayout);
        PainelLateralProdutosLayout.setHorizontalGroup(
            PainelLateralProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLateralProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelLateralProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelLateralProdutosLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblProdutos)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PainelLateralProdutosLayout.createSequentialGroup()
                        .addComponent(TabbedPaneProdutos)
                        .addContainerGap())))
        );
        PainelLateralProdutosLayout.setVerticalGroup(
            PainelLateralProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelLateralProdutosLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(lblProdutos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabbedPaneProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        TabbedPanePrincipal.addTab("Produtos", PainelLateralProdutos);

        TabbedPaneClientes.setForeground(new java.awt.Color(242, 242, 242));

        lblNomeCliente.setForeground(new java.awt.Color(51, 51, 51));
        lblNomeCliente.setText("Nome:");

        lblCPFCliente.setForeground(new java.awt.Color(51, 51, 51));
        lblCPFCliente.setText("CPF:");

        lblTelefoneCliente.setForeground(new java.awt.Color(51, 51, 51));
        lblTelefoneCliente.setText("Telefone:");

        lblCepCliente.setForeground(new java.awt.Color(51, 51, 51));
        lblCepCliente.setText("CEP:");

        txtCepConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCepConsultarActionPerformed(evt);
            }
        });

        btnConsultarCliente.setText("Consultar");

        TableConsultarCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableConsultarCliente);

        btnIncluirCliente.setText("Incluir");

        btnAlterarCliente.setText("Alterar");

        btnExcluirCliente.setText("Excluir");

        javax.swing.GroupLayout PainelConsultaClientesLayout = new javax.swing.GroupLayout(PainelConsultaClientes);
        PainelConsultaClientes.setLayout(PainelConsultaClientesLayout);
        PainelConsultaClientesLayout.setHorizontalGroup(
            PainelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelConsultaClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(PainelConsultaClientesLayout.createSequentialGroup()
                        .addComponent(btnIncluirCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAlterarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluirCliente)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PainelConsultaClientesLayout.createSequentialGroup()
                        .addGroup(PainelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PainelConsultaClientesLayout.createSequentialGroup()
                                .addComponent(lblNomeCliente)
                                .addGap(18, 18, 18)
                                .addComponent(txtNomeClienteConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PainelConsultaClientesLayout.createSequentialGroup()
                                .addComponent(lblCPFCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCpfConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(PainelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelConsultaClientesLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PainelConsultaClientesLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblCepCliente)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTelefoneConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(txtCepConsultar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(btnConsultarCliente)))
                .addContainerGap())
        );
        PainelConsultaClientesLayout.setVerticalGroup(
            PainelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelConsultaClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeCliente)
                    .addComponent(txtNomeClienteConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefoneCliente)
                    .addComponent(txtTelefoneConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(PainelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPFCliente)
                    .addComponent(txtCpfConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCepCliente)
                    .addComponent(btnConsultarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCepConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluirCliente)
                    .addComponent(btnAlterarCliente)
                    .addComponent(btnExcluirCliente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabbedPaneClientes.addTab("Consulta", PainelConsultaClientes);

        lblNome.setForeground(new java.awt.Color(51, 51, 51));
        lblNome.setText("Nome:");

        lblCPF.setForeground(new java.awt.Color(51, 51, 51));
        lblCPF.setText("CPF:");

        lblTel.setForeground(new java.awt.Color(51, 51, 51));
        lblTel.setText("Telefone:");

        lblEmail.setForeground(new java.awt.Color(51, 51, 51));
        lblEmail.setText("E-mail:");

        lblSexo.setForeground(new java.awt.Color(51, 51, 51));
        lblSexo.setText("Sexo:");

        lblEstadoCiv.setForeground(new java.awt.Color(51, 51, 51));
        lblEstadoCiv.setText("Estado civil:");

        lblDataNasc.setForeground(new java.awt.Color(51, 51, 51));
        lblDataNasc.setText("Data de nasc:");

        txtNomeClienteDigitar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeClienteDigitarFocusLost(evt);
            }
        });

        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        buttonGroupSexo.add(rbtnFemininoCliente);
        rbtnFemininoCliente.setForeground(new java.awt.Color(51, 51, 51));
        rbtnFemininoCliente.setText("Feminino");

        buttonGroupSexo.add(rbtnMasculinoCliente);
        rbtnMasculinoCliente.setForeground(new java.awt.Color(51, 51, 51));
        rbtnMasculinoCliente.setText("Masculino");
        rbtnMasculinoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMasculinoClienteActionPerformed(evt);
            }
        });

        cboEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Solteiro(a)", "Casado(a)", "Divorciado(a)", "Viúvo(a)" }));

        try {
            fTxtDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fTxtDataNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fTxtDataNascimentoFocusLost(evt);
            }
        });

        lblCep.setForeground(new java.awt.Color(51, 51, 51));
        lblCep.setText("CEP:");

        lblLogradouro.setForeground(new java.awt.Color(51, 51, 51));
        lblLogradouro.setText("Logradouro:");

        lblBairro.setForeground(new java.awt.Color(51, 51, 51));
        lblBairro.setText("Bairro:");

        lblCidade.setForeground(new java.awt.Color(51, 51, 51));
        lblCidade.setText("Cidade:");

        lblEstado.setForeground(new java.awt.Color(51, 51, 51));
        lblEstado.setText("Estado:");

        lblPais.setForeground(new java.awt.Color(51, 51, 51));
        lblPais.setText("País:");

        txtLogradouro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLogradouroFocusLost(evt);
            }
        });

        txtBairro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBairroFocusLost(evt);
            }
        });
        txtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroActionPerformed(evt);
            }
        });

        txtCidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCidadeFocusLost(evt);
            }
        });

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblStatusCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblStatusCliente.setForeground(new java.awt.Color(51, 255, 0));
        lblStatusCliente.setText("STATUS: VÁLIDO");

        try {
            fTxtCpfDigitar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fTxtCpfDigitar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fTxtCpfDigitarFocusLost(evt);
            }
        });
        fTxtCpfDigitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fTxtCpfDigitarActionPerformed(evt);
            }
        });

        try {
            fTxtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)# ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fTxtTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fTxtTelefoneFocusLost(evt);
            }
        });
        fTxtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fTxtTelefoneActionPerformed(evt);
            }
        });

        try {
            fTxtCepDigitar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fTxtCepDigitar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fTxtCepDigitarFocusLost(evt);
            }
        });

        cboPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Brasil" }));

        cboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceará", "Distrito Federal", "Espírito Santo", "Goiás", "Maranhão", "Mato Grosso", "Mato Grosso do Sul", "Minas Gerais", "Pará", "Paraíba", "Paraná", "Pernambuco", "Piauí", "Rio de Janeiro", "Rio Grande do Norte", "Rio Grande do Sul", "Rondônia", "Roraima", "Santa Catarina", "São Paulo", "Sergipe", "Tocantins" }));

        lblNumeroDigitar.setForeground(new java.awt.Color(51, 51, 51));
        lblNumeroDigitar.setText("Número:");

        fTxtNumeroDigitar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        fTxtNumeroDigitar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fTxtNumeroDigitarFocusLost(evt);
            }
        });
        fTxtNumeroDigitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fTxtNumeroDigitarActionPerformed(evt);
            }
        });

        lblComplemento.setForeground(new java.awt.Color(51, 51, 51));
        lblComplemento.setText("Complemento:");

        javax.swing.GroupLayout PainelDigitarClientesLayout = new javax.swing.GroupLayout(PainelDigitarClientes);
        PainelDigitarClientes.setLayout(PainelDigitarClientesLayout);
        PainelDigitarClientesLayout.setHorizontalGroup(
            PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelDigitarClientesLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelDigitarClientesLayout.createSequentialGroup()
                        .addComponent(lblStatusCliente)
                        .addGap(118, 118, 118)
                        .addComponent(btnOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PainelDigitarClientesLayout.createSequentialGroup()
                        .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelDigitarClientesLayout.createSequentialGroup()
                                .addComponent(lblDataNasc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fTxtDataNascimento))
                            .addGroup(PainelDigitarClientesLayout.createSequentialGroup()
                                .addComponent(lblEstadoCiv)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboEstadoCivil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(PainelDigitarClientesLayout.createSequentialGroup()
                                .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNome)
                                    .addComponent(lblCPF)
                                    .addComponent(lblTel)
                                    .addComponent(lblEmail)
                                    .addComponent(lblSexo))
                                .addGap(26, 26, 26)
                                .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmail)
                                    .addComponent(txtNomeClienteDigitar)
                                    .addComponent(fTxtCpfDigitar)
                                    .addComponent(fTxtTelefone)))
                            .addGroup(PainelDigitarClientesLayout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(rbtnFemininoCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(rbtnMasculinoCliente)
                                .addGap(26, 26, 26)))
                        .addGap(36, 36, 36)
                        .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelDigitarClientesLayout.createSequentialGroup()
                                .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCep)
                                    .addComponent(lblLogradouro)
                                    .addComponent(lblNumeroDigitar))
                                .addGap(21, 21, 21)
                                .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fTxtNumeroDigitar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtLogradouro, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fTxtCepDigitar, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelDigitarClientesLayout.createSequentialGroup()
                                .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEstado)
                                    .addComponent(lblPais))
                                .addGap(48, 48, 48)
                                .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboEstado, 0, 165, Short.MAX_VALUE)
                                    .addComponent(cboPais, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelDigitarClientesLayout.createSequentialGroup()
                                .addComponent(lblComplemento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtComplemento))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelDigitarClientesLayout.createSequentialGroup()
                                .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBairro)
                                    .addComponent(lblCidade))
                                .addGap(46, 46, 46)
                                .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBairro)
                                    .addComponent(txtCidade))))
                        .addGap(44, 44, 44))))
        );
        PainelDigitarClientesLayout.setVerticalGroup(
            PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelDigitarClientesLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNomeClienteDigitar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCep)
                    .addComponent(fTxtCepDigitar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPF)
                    .addComponent(lblLogradouro)
                    .addComponent(fTxtCpfDigitar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTel)
                    .addComponent(fTxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblNumeroDigitar)
                        .addComponent(fTxtNumeroDigitar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelDigitarClientesLayout.createSequentialGroup()
                        .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtnFemininoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtnMasculinoCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEstadoCiv))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fTxtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataNasc))
                        .addGap(84, 84, 84))
                    .addGroup(PainelDigitarClientesLayout.createSequentialGroup()
                        .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblComplemento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBairro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCidade))
                        .addGap(9, 9, 9)
                        .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEstado))
                        .addGap(14, 14, 14)
                        .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPais))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(PainelDigitarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatusCliente)
                    .addComponent(btnOK)
                    .addComponent(btnCancelar))
                .addGap(42, 42, 42))
        );

        TabbedPaneClientes.addTab("Digitar", PainelDigitarClientes);

        lblClientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblClientes.setForeground(new java.awt.Color(51, 51, 51));
        lblClientes.setText("Clientes");

        javax.swing.GroupLayout PainelLateralClienteLayout = new javax.swing.GroupLayout(PainelLateralCliente);
        PainelLateralCliente.setLayout(PainelLateralClienteLayout);
        PainelLateralClienteLayout.setHorizontalGroup(
            PainelLateralClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLateralClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelLateralClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TabbedPaneClientes)
                    .addGroup(PainelLateralClienteLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblClientes)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PainelLateralClienteLayout.setVerticalGroup(
            PainelLateralClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelLateralClienteLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(lblClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabbedPaneClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        TabbedPanePrincipal.addTab("Clientes", PainelLateralCliente);

        javax.swing.GroupLayout PainelLateralVendasLayout = new javax.swing.GroupLayout(PainelLateralVendas);
        PainelLateralVendas.setLayout(PainelLateralVendasLayout);
        PainelLateralVendasLayout.setHorizontalGroup(
            PainelLateralVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 649, Short.MAX_VALUE)
        );
        PainelLateralVendasLayout.setVerticalGroup(
            PainelLateralVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );

        TabbedPanePrincipal.addTab("Vendas", PainelLateralVendas);

        javax.swing.GroupLayout PainelLateralRelatoriosLayout = new javax.swing.GroupLayout(PainelLateralRelatorios);
        PainelLateralRelatorios.setLayout(PainelLateralRelatoriosLayout);
        PainelLateralRelatoriosLayout.setHorizontalGroup(
            PainelLateralRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 649, Short.MAX_VALUE)
        );
        PainelLateralRelatoriosLayout.setVerticalGroup(
            PainelLateralRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );

        TabbedPanePrincipal.addTab("Relatórios", PainelLateralRelatorios);

        PainelHeader.setToolTipText("Painel header");

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        lblHeader.setForeground(new java.awt.Color(51, 51, 51));
        lblHeader.setText("Xablau tech");

        imgLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hacker (1).png"))); // NOI18N

        javax.swing.GroupLayout PainelHeaderLayout = new javax.swing.GroupLayout(PainelHeader);
        PainelHeader.setLayout(PainelHeaderLayout);
        PainelHeaderLayout.setHorizontalGroup(
            PainelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PainelHeaderLayout.setVerticalGroup(
            PainelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelHeaderLayout.createSequentialGroup()
                .addGroup(PainelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addGroup(PainelHeaderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PainelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        PainelFooter.setToolTipText("Painel header");

        lblFooter.setForeground(new java.awt.Color(51, 51, 51));
        lblFooter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFooter.setText("@Xablau Tech - Direitos reservardos - 2024");

        javax.swing.GroupLayout PainelFooterLayout = new javax.swing.GroupLayout(PainelFooter);
        PainelFooter.setLayout(PainelFooterLayout);
        PainelFooterLayout.setHorizontalGroup(
            PainelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PainelFooterLayout.setVerticalGroup(
            PainelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFooter, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TabbedPanePrincipal)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PainelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PainelFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabbedPanePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");
        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroActionPerformed

    private void rbtnMasculinoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMasculinoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnMasculinoClienteActionPerformed

    private void txtCepConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCepConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCepConsultarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void txtEstoqueProdutoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstoqueProdutoKeyTyped
        char letra = evt.getKeyChar();

        if(!Validacao.validaNumero(evt, letra)) {    
            this.lblStatusProduto.setText("STATUS: ESTOQUE INVÁLIDO");
            this.lblStatusProduto.setForeground(Color.red);
        } else {
            this.lblStatusProduto.setText("STATUS: VÁLIDO");
            this.lblStatusProduto.setForeground(Color.green);
        }
    }//GEN-LAST:event_txtEstoqueProdutoKeyTyped

    private void txtNomeProdutoDigitarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeProdutoDigitarFocusLost
        if(!Validacao.validaStringVazia(this.txtNomeProdutoDigitar.getText())) {
            this.lblStatusProduto.setText("STATUS: NOME INVÁLIDO");
            this.lblStatusProduto.setForeground(Color.red);
        } else {
            this.lblStatusProduto.setText("STATUS: VÁLIDO");
            this.lblStatusProduto.setForeground(Color.green);
        }
    }//GEN-LAST:event_txtNomeProdutoDigitarFocusLost

    private void txtCategoriaProdutoDigitarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCategoriaProdutoDigitarFocusLost
        if(!Validacao.validaStringVazia(this.txtCategoriaProdutoDigitar.getText())) {
            this.lblStatusProduto.setText("STATUS: CATEGORIA INVÁLIDO");
            this.lblStatusProduto.setForeground(Color.red);
        } else {
            this.lblStatusProduto.setText("STATUS: VÁLIDO");
            this.lblStatusProduto.setForeground(Color.green);
        }
    }//GEN-LAST:event_txtCategoriaProdutoDigitarFocusLost

    private void btnCancelarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarProdutoActionPerformed
        // Zera os campos
        limpaCamposProduto();
        
        // Volta para guia de consulta
        this.TabbedPaneProdutos.setSelectedIndex(0);
        this.lblAcaoDigitar.setText("Inserir");
    }//GEN-LAST:event_btnCancelarProdutoActionPerformed

    private void btnOkProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkProdutoActionPerformed
        String nome = this.txtNomeProdutoDigitar.getText().trim();
        String modelo = this.txtModeloProdutoDigitar.getText().trim();
        String categoria = this.txtCategoriaProdutoDigitar.getText().trim();
        String fabricante = this.txtFabricanteProduto.getText().trim();
        String cor = this.cboCor.getSelectedItem().toString();
        String preco = this.txtPrecoProduto.getText().trim();
        String estoqueString = this.txtEstoqueProduto.getText().trim();
                
        if (validaCamposObrigatoriosProduto()) {
            return;
        }
        
        // Converte apenas se estiver preenchido
        int estoque = Integer.parseInt(estoqueString);
        
        DefaultTableModel tabela = (DefaultTableModel)this.tblProdutos.getModel();
        if (this.lblAcaoDigitar.getText().equals("Inserir")) {
            tabela.addRow(new Object[]{nome, modelo, categoria, preco, estoque, fabricante, cor});
            limpaCamposProduto();
            JOptionPane.showMessageDialog(rootPane, "Produto inserido com sucesso");
        } else {
            int linha = this.tblProdutos.getSelectedRow();
            tabela.setValueAt(nome, linha, 0);
            tabela.setValueAt(modelo, linha, 1);
            tabela.setValueAt(categoria, linha, 2);
            tabela.setValueAt(preco, linha, 3);
            tabela.setValueAt(estoque, linha, 4);
            tabela.setValueAt(fabricante, linha, 5);
            tabela.setValueAt(cor, linha, 6);
       
            limpaCamposProduto();     
            JOptionPane.showMessageDialog(rootPane, "Produto alterado com sucesso");
            this.TabbedPaneProdutos.setSelectedIndex(0);
            this.lblAcaoDigitar.setText("Inserir");
        }
    }//GEN-LAST:event_btnOkProdutoActionPerformed
    
    private boolean validaCamposObrigatoriosProduto() {
        String nome = this.txtNomeProdutoDigitar.getText().trim();
        String categoria = this.txtCategoriaProdutoDigitar.getText().trim();
        String preco = this.txtPrecoProduto.getText().trim();
        String estoque = this.txtEstoqueProduto.getText().trim();
        
        if (nome.equals("") || categoria.equals("") || preco.equals("") || estoque.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos obrigatórios");
            return true;
        }
        
        return false;
    }
    
    private void limpaCamposProduto() {
        this.txtNomeProdutoDigitar.setText("");
        this.txtModeloProdutoDigitar.setText("");
        this.txtCategoriaProdutoDigitar.setText("");
        this.txtFabricanteProduto.setText("");
        this.cboCor.setSelectedIndex(0);
        this.txtPrecoProduto.setValue(null);
        this.txtPrecoProduto.setText("");
        this.txtEstoqueProduto.setText("");
    }
    
    private void btnIncluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirProdutoActionPerformed
        this.TabbedPaneProdutos.setSelectedIndex(1);
        this.lblAcaoDigitar.setText("Inserir");
    }//GEN-LAST:event_btnIncluirProdutoActionPerformed

    private void btnExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirProdutoActionPerformed
        if (this.tblProdutos.getRowCount() <= 0) {
            JOptionPane.showMessageDialog(rootPane, "Não há itens a serem excluídos");
            return;
        }
        
        DefaultTableModel tabela = (DefaultTableModel)this.tblProdutos.getModel();
        
        Object[] opcoes = {"Sim, quero excluir", "Não, cancelar"};
        int escolha = JOptionPane.showOptionDialog(
                rootPane, 
                "Tem certeza que deseja excluir esse item?", 
                "Excluir item", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[0]);
        
        if(escolha == 1 || escolha == JOptionPane.CLOSED_OPTION) {
            return;
        }
        
        tabela.removeRow(this.tblProdutos.getSelectedRow());
    }//GEN-LAST:event_btnExcluirProdutoActionPerformed

    private void btnAlterarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarProdutoActionPerformed
        if (this.tblProdutos.getRowCount() <= 0) {
            JOptionPane.showMessageDialog(rootPane, "Não há itens a serem alterados");
            return;
        }
        
        DefaultTableModel tabela = (DefaultTableModel)this.tblProdutos.getModel();
        int linha = this.tblProdutos.getSelectedRow();
        
        this.txtNomeProdutoDigitar.setText(tabela.getValueAt(linha, 0).toString());
        this.txtModeloProdutoDigitar.setText(tabela.getValueAt(linha, 1).toString());
        this.txtCategoriaProdutoDigitar.setText(tabela.getValueAt(linha, 2).toString());
        this.txtPrecoProduto.setText(tabela.getValueAt(linha, 3).toString());
        this.txtEstoqueProduto.setText(tabela.getValueAt(linha, 4).toString());
        this.txtFabricanteProduto.setText(tabela.getValueAt(linha, 5).toString());
        
        // passa por todos items do combo comparando se o item atual, 
        // é igual o valor na tabela
        for (int i = 0; i < this.cboCor.getItemCount(); i++) {
            this.cboCor.setSelectedIndex(i);
            
            if(this.cboCor.getSelectedItem().toString().equals(tabela.getValueAt(linha, 6).toString())) {
                this.cboCor.setSelectedIndex(i);
                break;
            }
        }

        this.lblAcaoDigitar.setText("Alterar");
        this.TabbedPaneProdutos.setSelectedIndex(1);
    }//GEN-LAST:event_btnAlterarProdutoActionPerformed

    private void bntConsultarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntConsultarProdutoActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Em desenvolvimento...");
    }//GEN-LAST:event_bntConsultarProdutoActionPerformed

    private void txtNomeClienteDigitarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeClienteDigitarFocusLost
        if(!Validacao.validaStringVazia(this.txtNomeClienteDigitar.getText())) {
            this.lblStatusCliente.setText("STATUS: NOME INVÁLIDO");
            this.lblStatusCliente.setForeground(Color.red);
        }else {
            this.lblStatusCliente.setText("STATUS: VÁLIDO");
            this.lblStatusCliente.setForeground(Color.green);
        }
    }//GEN-LAST:event_txtNomeClienteDigitarFocusLost

    private void fTxtCpfDigitarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fTxtCpfDigitarFocusLost
        String cpf = fTxtCpfDigitar.getText();
        
        if(cpf.equals("   .   .   -  ")){
            this.lblStatusCliente.setText("STATUS: CPF INVÁLIDO");
            this.lblStatusCliente.setForeground(Color.red);
        }else {
            this.lblStatusCliente.setText("STATUS: VÁLIDO");
            this.lblStatusCliente.setForeground(Color.green);
        }
    }//GEN-LAST:event_fTxtCpfDigitarFocusLost

    private void fTxtCpfDigitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fTxtCpfDigitarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fTxtCpfDigitarActionPerformed

    private void fTxtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fTxtTelefoneActionPerformed
        
    }//GEN-LAST:event_fTxtTelefoneActionPerformed

    private void fTxtTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fTxtTelefoneFocusLost
        String telefone = fTxtTelefone.getText();
        
        if(telefone.equals("(  )      -    ")){
            this.lblStatusCliente.setText("STATUS: TELEFONE INVÁLIDO");
            this.lblStatusCliente.setForeground(Color.red);
        }else {
            this.lblStatusCliente.setText("STATUS: VÁLIDO");
            this.lblStatusCliente.setForeground(Color.green);
        }
    }//GEN-LAST:event_fTxtTelefoneFocusLost

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        if(!Validacao.validaStringVazia(this.txtEmail.getText())) {
            this.lblStatusCliente.setText("STATUS: EMAIL INVÁLIDO");
            this.lblStatusCliente.setForeground(Color.red);
        } else {
            this.lblStatusCliente.setText("STATUS: VÁLIDO");
            this.lblStatusCliente.setForeground(Color.green);
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void fTxtDataNascimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fTxtDataNascimentoFocusLost
        String dataNascimento = fTxtDataNascimento.getText();
        
        if(dataNascimento.equals("  /  /    ")){
            this.lblStatusCliente.setText("STATUS: DATA DE NASCIMENTO INVÁLIDA");
            this.lblStatusCliente.setForeground(Color.red);
        }else {
            this.lblStatusCliente.setText("STATUS: VÁLIDO");
            this.lblStatusCliente.setForeground(Color.green);
        }
        
    }//GEN-LAST:event_fTxtDataNascimentoFocusLost

    private void fTxtCepDigitarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fTxtCepDigitarFocusLost
        String cep = fTxtCepDigitar.getText();
        
        if(cep.equals("     -   ")){
            this.lblStatusCliente.setText("STATUS: CEP INVÁLIDO");
            this.lblStatusCliente.setForeground(Color.red);
        }else {
            this.lblStatusCliente.setText("STATUS: VÁLIDO");
            this.lblStatusCliente.setForeground(Color.green);
        }
    }//GEN-LAST:event_fTxtCepDigitarFocusLost

    private void txtLogradouroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLogradouroFocusLost
        if(!Validacao.validaStringVazia(this.txtLogradouro.getText())) {
            this.lblStatusCliente.setText("STATUS: LOGRADOURO INVÁLIDO");
            this.lblStatusCliente.setForeground(Color.red);
        } else {
            this.lblStatusCliente.setText("STATUS: VÁLIDO");
            this.lblStatusCliente.setForeground(Color.green);
        }
    }//GEN-LAST:event_txtLogradouroFocusLost

    private void PainelLateralProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PainelLateralProdutosMouseClicked
        
    }//GEN-LAST:event_PainelLateralProdutosMouseClicked

    private void fTxtNumeroDigitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fTxtNumeroDigitarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fTxtNumeroDigitarActionPerformed

    private void fTxtNumeroDigitarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fTxtNumeroDigitarFocusLost
    
        if(fTxtNumeroDigitar.getText().isEmpty()){
            this.lblStatusCliente.setText("STATUS: NÚMERO INVÁLIDO");
            this.lblStatusCliente.setForeground(Color.red);
        } else {
            this.lblStatusCliente.setText("STATUS: VÁLIDO");
            this.lblStatusCliente.setForeground(Color.green);
        }
    }//GEN-LAST:event_fTxtNumeroDigitarFocusLost

    private void txtBairroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBairroFocusLost
        if(!Validacao.validaStringVazia(this.txtBairro.getText())) {
            this.lblStatusCliente.setText("STATUS: BAIRRO INVÁLIDO");
            this.lblStatusCliente.setForeground(Color.red);
        } else {
            this.lblStatusCliente.setText("STATUS: VÁLIDO");
            this.lblStatusCliente.setForeground(Color.green);
        }
    }//GEN-LAST:event_txtBairroFocusLost

    private void txtCidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCidadeFocusLost
        if(!Validacao.validaStringVazia(this.txtCidade.getText())) {
            this.lblStatusCliente.setText("STATUS: CIDADE INVÁLIDA");
            this.lblStatusCliente.setForeground(Color.red);
        } else {
            this.lblStatusCliente.setText("STATUS: VÁLIDO");
            this.lblStatusCliente.setForeground(Color.green);
        }
    }//GEN-LAST:event_txtCidadeFocusLost

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        JOptionPane.showMessageDialog(rootPane,"Em desenvolvimento...");
        // Fazer lógica para válidar input e inserir linha
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // Zera os campos
        //Não está zerando os campos Formatted Field criados (variaveis que começam com fTXT)
        this.txtNomeClienteDigitar.setText("");
        this.fTxtCpfDigitar.setText("");
        this.fTxtTelefone.setText("");
        this.txtEmail.setText("");
        this.buttonGroupSexo.clearSelection();
        this.cboEstadoCivil.setSelectedIndex(0);
        this.fTxtDataNascimento.setText("");
        this.fTxtCepDigitar.setText("");
        this.txtLogradouro.setText("");
        this.fTxtNumeroDigitar.setText("");
        this.txtComplemento.setText("");
        this.txtBairro.setText("");
        this.txtCidade.setText("");
        this.cboEstado.setSelectedIndex(0);
        this.cboPais.setSelectedIndex(0);
        
        // Volta para guia de consulta de clientes
        this.TabbedPaneClientes.setSelectedIndex(0);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtEstoqueProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEstoqueProdutoFocusLost
        if (!Validacao.validaConversaoInteiro(this.txtEstoqueProduto.getText())) {
            this.lblStatusProduto.setText("STATUS: ESTOQUE INVÁLIDO");
            this.lblStatusProduto.setForeground(Color.red);
            this.txtEstoqueProduto.setText("");
        } else {
            this.lblStatusProduto.setText("STATUS: VÁLIDO");
            this.lblStatusProduto.setForeground(Color.green);
        }
    }//GEN-LAST:event_txtEstoqueProdutoFocusLost

    private void txtPrecoProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecoProdutoFocusLost
        if (Validacao.validaStringVazia(this.txtPrecoProduto.getText())) {
            this.lblStatusProduto.setText("STATUS: ESTOQUE INVÁLIDO");
            this.lblStatusProduto.setForeground(Color.red);
            this.txtPrecoProduto.setText("");
            this.txtPrecoProduto.setValue(null);
        } else {
            this.lblStatusProduto.setText("STATUS: VÁLIDO");
            this.lblStatusProduto.setForeground(Color.green);
        }
    }//GEN-LAST:event_txtPrecoProdutoFocusLost

    private void txtPrecoProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecoProdutoKeyPressed
      
    }//GEN-LAST:event_txtPrecoProdutoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerencial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerencial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerencial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerencial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGerencial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelConsultaClientes;
    private javax.swing.JPanel PainelConsultaProdutos;
    private javax.swing.JPanel PainelDigitarClientes;
    private javax.swing.JPanel PainelDigitarProdutos;
    private javax.swing.JPanel PainelFooter;
    private javax.swing.JPanel PainelHeader;
    private javax.swing.JPanel PainelLateralCliente;
    private javax.swing.JPanel PainelLateralProdutos;
    private javax.swing.JPanel PainelLateralRelatorios;
    private javax.swing.JPanel PainelLateralVendas;
    private javax.swing.JTabbedPane TabbedPaneClientes;
    private javax.swing.JTabbedPane TabbedPanePrincipal;
    private javax.swing.JTabbedPane TabbedPaneProdutos;
    private javax.swing.JTable TableConsultarCliente;
    private javax.swing.JButton bntConsultarProduto;
    private javax.swing.JButton btnAlterarCliente;
    private javax.swing.JButton btnAlterarProduto;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelarProduto;
    private javax.swing.JButton btnConsultarCliente;
    private javax.swing.JButton btnExcluirCliente;
    private javax.swing.JButton btnExcluirProduto;
    private javax.swing.JButton btnIncluirCliente;
    private javax.swing.JButton btnIncluirProduto;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnOkProduto;
    private javax.swing.JToggleButton btnSair;
    private javax.swing.ButtonGroup buttonGroupSexo;
    private javax.swing.JComboBox<String> cboCor;
    private javax.swing.JComboBox<String> cboEstado;
    private javax.swing.JComboBox<String> cboEstadoCivil;
    private javax.swing.JComboBox<String> cboPais;
    private javax.swing.JFormattedTextField fTxtCepDigitar;
    private javax.swing.JFormattedTextField fTxtCpfDigitar;
    private javax.swing.JFormattedTextField fTxtDataNascimento;
    private javax.swing.JFormattedTextField fTxtNumeroDigitar;
    private javax.swing.JFormattedTextField fTxtTelefone;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAcaoDigitar;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCPFCliente;
    private javax.swing.JLabel lblCategoriaPD;
    private javax.swing.JLabel lblCategoriaProduto;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCepCliente;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblCorPD;
    private javax.swing.JLabel lblDataNasc;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEstadoCiv;
    private javax.swing.JLabel lblEstoquePD;
    private javax.swing.JLabel lblFabricantePD;
    private javax.swing.JLabel lblFooter;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblLogradouro;
    private javax.swing.JLabel lblModeloPD;
    private javax.swing.JLabel lblModeloProduto;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblNomePD;
    private javax.swing.JLabel lblNomeProduto;
    private javax.swing.JLabel lblNumeroDigitar;
    private javax.swing.JLabel lblPais;
    private javax.swing.JLabel lblPrecoPD;
    private javax.swing.JLabel lblPrecoProduto;
    private javax.swing.JLabel lblProdutos;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblStatusCliente;
    private javax.swing.JLabel lblStatusProduto;
    private javax.swing.JLabel lblTel;
    private javax.swing.JLabel lblTelefoneCliente;
    private javax.swing.JLabel lblateProduto;
    private javax.swing.JRadioButton rbtnFemininoCliente;
    private javax.swing.JRadioButton rbtnMasculinoCliente;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCategoriaProdutoConsultar;
    private javax.swing.JTextField txtCategoriaProdutoDigitar;
    private javax.swing.JTextField txtCepConsultar;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtCpfConsultar;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEstoqueProduto;
    private javax.swing.JTextField txtFabricanteProduto;
    private javax.swing.JTextField txtLogradouro;
    private javax.swing.JTextField txtModeloProdutoConsultar;
    private javax.swing.JTextField txtModeloProdutoDigitar;
    private javax.swing.JTextField txtNomeClienteConsultar;
    private javax.swing.JTextField txtNomeClienteDigitar;
    private javax.swing.JTextField txtNomeProdutoConsultar;
    private javax.swing.JTextField txtNomeProdutoDigitar;
    private javax.swing.JTextField txtPrecoATE;
    private javax.swing.JTextField txtPrecoDE;
    private javax.swing.JFormattedTextField txtPrecoProduto;
    private javax.swing.JTextField txtTelefoneConsultar;
    // End of variables declaration//GEN-END:variables
}
